apiVersion: v1
kind: Pod
metadata:
  name: pod-example1
  labels:
    env: qa1
    tier: frontend1
  annotations:
    created-by: "cluster admin"
spec:
  containers:
  - name: myapp
    image: ikubernetes/myapp:v1
    imagePullPolicy: Never     
    ports:
    - name: http
      containerPort: 80
      protocol: TCP
    command: ["/bin/sh"]
    args: ["-c", "while true; do sleep 30; done"]
    env:
    - name: REDIS_HOST
      value: do.macOS
    - name: LOG_LEVEL
      value: info