apiVersion: v1
kind: Service
metadata:
  name: myapp-svc-lb
spec:
  type: LoadBalancer
  selector:
    app: myapp  
  loadBalancerIP: 127.0.0.2
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
    # nodePort: 30002